skillMetadata:
  sections:
    - name: Notification Settings
      fields:
        - name: speak_alarm
          type: checkbox
          label: Speak alarm notifications (unchecked - only plays alarm sound)
          value: false
        - name: speak_timer
          type: checkbox
          label: Speak timer notifications (unchecked - only plays timer sound)
          value: true
        - name: sound_alarm
          type: text
          label: Alarm audio resource file
          value: constant_beep.mp3
        - name: sound_timer
          type: text
          label: Timer audio resource file
          value: beep4.mp3
        - name: quiet_hours
          type: checkbox
          label: Quiet Hours (mutes all notifications until disabled)
          value: false
        - name: snooze_mins
          type: number
          label: Default snooze duration in minutes
          value: 15
        - name: timeout_min
          type: number
          label: Default alert timeout duration in minutes
          value: 2
        - name: priority_cutoff
          type: number
          label: Default alert priority cutoff
          value: 8
    - name: CalDAV
      fields:
        - name: service_label
          type: label
          label: >
            <p>Which caldav services do you want to use? (comma separated list)
            The credentials have to be set in the corresponding skill CONFIG folder.
            (default ~/.config/<mycroft-distribution>/skills/<skill>/dav_credentials.json)
            Needs skill reload</p>
        - name: services
          type: text
          label: Services
          value: ""
        - name: frequency
          type: number
          label: Sync frequency (minutes)
          value: 15
        - name: sync_ask
          type: checkbox
          label: Ask whether to sync alert
          value: false