"""E2E intent-routing tests for ovos-skill-alerts.

Auto-generated by tools/gen_ovoscope_tests.py
Run: pytest test/end2end/ -v
"""
from unittest import TestCase

from ovos_bus_client.message import Message
from ovos_bus_client.session import Session
from ovoscope import End2EndTest, get_minicroft

SKILL_ID = "ovos-skill-alerts.openvoiceos"
LANG = "en-US"

# A single MiniCroft is booted once for the whole module and shared across
# every TestCase below. Booting one per class (the original generated
# pattern) meant ~30 separate MiniCroft boots per CI run, which is what made
# this suite time out / get killed in CI even with parallel workers disabled.
_MODULE_MINICROFT = None


def setUpModule():
    global _MODULE_MINICROFT
    _MODULE_MINICROFT = get_minicroft([SKILL_ID])


def tearDownModule():
    global _MODULE_MINICROFT
    if _MODULE_MINICROFT is not None:
        _MODULE_MINICROFT.stop()
        _MODULE_MINICROFT = None


class _IntentRoutingMixin:
    """Shared MiniCroft setup."""

    @classmethod
    def setUpClass(cls):
        cls.minicroft = _MODULE_MINICROFT

    @classmethod
    def tearDownClass(cls):
        pass


    def _assert_padatious(self, utterance: str, intent_file: str):
        intent_msg_type = f"{SKILL_ID}:{intent_file}"
        session = Session(f"e2e-en_us-{intent_file}-{hash(utterance)}")
        session.lang = LANG
        session.pipeline = [
            "ovos-padatious-pipeline-plugin-high",
            "ovos-padatious-pipeline-plugin-medium",
            "ovos-padatious-pipeline-plugin-low",
        ]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        test = End2EndTest(
            minicroft=self.minicroft,
            skill_ids=[SKILL_ID],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            source_message=message,
            activation_points=[intent_msg_type],
            test_msg_context=False,
            test_message_number=False,
            ignore_messages=["speak", "mycroft.audio.play_sound"],
            expected_messages=[
                message,
                Message(f"{SKILL_ID}.activate", {}, {"skill_id": SKILL_ID}),
                Message(intent_msg_type, {}, {"skill_id": SKILL_ID}),
                Message("mycroft.skill.handler.start", {}, {"skill_id": SKILL_ID}),
                Message("mycroft.skill.handler.complete", {}, {"skill_id": SKILL_ID}),
                Message("ovos.utterance.handled", {}, {"skill_id": SKILL_ID}),
            ],
        )
        test.execute(timeout=30)


    def _assert_adapt(self, utterance: str, intent_label: str = ''):
        intent_msg_type = f"{SKILL_ID}:{intent_label}" if intent_label else None
        session = Session(f"e2e-en_us-adapt-{hash(utterance)}")
        session.lang = LANG
        session.pipeline = [
            "ovos-adapt-pipeline-plugin-high",
            "ovos-adapt-pipeline-plugin-medium",
            "ovos-adapt-pipeline-plugin-low",
        ]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        activation_points = [intent_msg_type] if intent_msg_type else []
        expected = [
            message,
            Message(f"{SKILL_ID}.activate", {}, {"skill_id": SKILL_ID}),
            Message("mycroft.skill.handler.start", {}, {"skill_id": SKILL_ID}),
            Message("mycroft.skill.handler.complete", {}, {"skill_id": SKILL_ID}),
            Message("ovos.utterance.handled", {}, {"skill_id": SKILL_ID}),
        ]
        if intent_msg_type:
            expected.insert(2, Message(intent_msg_type, {}, {"skill_id": SKILL_ID}))
        test = End2EndTest(
            minicroft=self.minicroft,
            skill_ids=[SKILL_ID],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            source_message=message,
            activation_points=activation_points,
            test_msg_context=False,
            test_message_number=False,
            ignore_messages=["speak", "mycroft.audio.play_sound"],
            expected_messages=expected,
        )
        test.execute(timeout=30)


    def _assert_simple(self, utterance: str):
        session = Session(f"e2e-en_us-simple-{hash(utterance)}")
        session.lang = LANG
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        test = End2EndTest(
            minicroft=self.minicroft,
            skill_ids=[SKILL_ID],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            source_message=message,
            expected_messages=["speak"],
        )
        test.execute(timeout=30)


class TestPadatious1_Missed_alerts_intent(_IntentRoutingMixin, TestCase):
    """Padatious intent: missed_alerts.intent"""
    def test_did_i_miss_any_alarms(self):
        self._assert_padatious(r"did i miss any alarms", r"missed_alerts.intent")

    def test_missed_any_reminder(self):
        self._assert_padatious(r"missed any reminder", r"missed_alerts.intent")

    def test_have_i_missed_any_timers(self):
        self._assert_padatious(r"have i missed any timers", r"missed_alerts.intent")

    def test_miss_any_events(self):
        self._assert_padatious(r"miss any events", r"missed_alerts.intent")

    def test_did_i_miss_a_alarm(self):
        self._assert_padatious(r"did i miss a alarm", r"missed_alerts.intent")

class TestAdapt2_Createalarm(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateAlarm"""
    def test_set_an_alarm(self):
        self._assert_adapt(r"set an alarm", r"CreateAlarm")

    def test_create_a_playback_alarm_every_weekday_wi(self):
        self._assert_adapt(r"create a playback alarm every weekday with my test script until next tuesday", r"CreateAlarm")

    def test_alarm_in_an_hour(self):
        self._assert_adapt(r"alarm in an hour", r"CreateAlarm")

    def test_alarm_daily_for_the_next_week_at_9_am(self):
        self._assert_adapt(r"alarm daily for the next week at 9 AM", r"CreateAlarm")

    def test_make_a_10_am_weekend_alarm(self):
        self._assert_adapt(r"make a 10 am weekend alarm", r"CreateAlarm")

class TestAdapt3_Createalarmalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateAlarmAlt"""
    def test_set_an_alarm(self):
        self._assert_adapt(r"set an alarm", r"CreateAlarmAlt")

    def test_create_a_playback_alarm_every_weekday_wi(self):
        self._assert_adapt(r"create a playback alarm every weekday with my test script until next tuesday", r"CreateAlarmAlt")

    def test_alarm_in_an_hour(self):
        self._assert_adapt(r"alarm in an hour", r"CreateAlarmAlt")

    def test_alarm_daily_for_the_next_week_at_9_am(self):
        self._assert_adapt(r"alarm daily for the next week at 9 AM", r"CreateAlarmAlt")

    def test_make_a_10_am_weekend_alarm(self):
        self._assert_adapt(r"make a 10 am weekend alarm", r"CreateAlarmAlt")

class TestAdapt4_Createocpalarm(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateOcpAlarm"""
    def test_wake_me_up_with_music(self):
        self._assert_adapt(r"wake me up with music", r"CreateOcpAlarm")

class TestAdapt5_Createocpalarmalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateOcpAlarmAlt"""
    def test_wake_me_up_with_music(self):
        self._assert_adapt(r"wake me up with music", r"CreateOcpAlarmAlt")

class TestAdapt6_Createtimer(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateTimer"""
    def test_set_a_timer(self):
        self._assert_adapt(r"set a timer", r"CreateTimer")

    def test_start_a_timer(self):
        self._assert_adapt(r"start a timer", r"CreateTimer")

    def test_create_a_baking_timer(self):
        self._assert_adapt(r"create a baking timer", r"CreateTimer")

    def test_make_a_5_hour_timer(self):
        self._assert_adapt(r"make a 5 hour timer", r"CreateTimer")

class TestAdapt7_Createreminder(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateReminder"""
    def test_set_a_playback_reminder_to_take_out_the_(self):
        self._assert_adapt(r"set a playback reminder to take out the trash daily at 5 pm until november", r"CreateReminder")

    def test_set_a_script_reminder_for_weekends_at_5_(self):
        self._assert_adapt(r"set a script reminder for weekends at 5 till next week", r"CreateReminder")

    def test_create_a_reminder_to_go_to_work_at_9_am_(self):
        self._assert_adapt(r"create a reminder to go to work at 9 am daily for the next month", r"CreateReminder")

    def test_remind_me_to_go_to_work_weekday_mornings(self):
        self._assert_adapt(r"remind me to go to work weekday mornings at 8", r"CreateReminder")

    def test_remind_me_every_day_to_check_for_test_fa(self):
        self._assert_adapt(r"remind me every day to check for test failures until 2024", r"CreateReminder")

class TestAdapt8_Createreminderalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateReminderAlt"""
    def test_set_a_playback_reminder_to_take_out_the_(self):
        self._assert_adapt(r"set a playback reminder to take out the trash daily at 5 pm until november", r"CreateReminderAlt")

    def test_set_a_script_reminder_for_weekends_at_5_(self):
        self._assert_adapt(r"set a script reminder for weekends at 5 till next week", r"CreateReminderAlt")

    def test_create_a_reminder_to_go_to_work_at_9_am_(self):
        self._assert_adapt(r"create a reminder to go to work at 9 am daily for the next month", r"CreateReminderAlt")

    def test_remind_me_to_go_to_work_weekday_mornings(self):
        self._assert_adapt(r"remind me to go to work weekday mornings at 8", r"CreateReminderAlt")

    def test_remind_me_every_day_to_check_for_test_fa(self):
        self._assert_adapt(r"remind me every day to check for test failures until 2024", r"CreateReminderAlt")

class TestAdapt9_Createevent(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateEvent"""
    def test_i_have_a_work_event_next_tuesday_at_7_pm(self):
        self._assert_adapt(r"I have a work event next tuesday at 7 PM", r"CreateEvent")

    def test_i_have_an_appointment_at_9_pm_every_week(self):
        self._assert_adapt(r"I have an appointment at 9 PM every weekend night until next year", r"CreateEvent")

    def test_create_a_daily_event_to_join_zoom_at_1_p(self):
        self._assert_adapt(r"create a daily event to join zoom at 1 PM for the next year", r"CreateEvent")

class TestAdapt10_Reschedulealert(_IntentRoutingMixin, TestCase):
    """Adapt intent: RescheduleAlert"""
    def test_move_the_baseball_event_to_08_00_pm(self):
        self._assert_adapt(r"move the baseball event to 08:00 pm", r"RescheduleAlert")

    def test_reschedule_the_next_event_two_hours_earl(self):
        self._assert_adapt(r"reschedule the next event two hours earlier", r"RescheduleAlert")

    def test_extend_the_pizza_timer_by_2_minutes(self):
        self._assert_adapt(r"extend the pizza timer by 2 minutes", r"RescheduleAlert")

    def test_decrease_the_bread_timer_by_5_minutes(self):
        self._assert_adapt(r"decrease the bread timer by 5 minutes", r"RescheduleAlert")

class TestAdapt11_Reschedulealertalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: RescheduleAlertAlt"""
    def test_move_the_baseball_event_to_08_00_pm(self):
        self._assert_adapt(r"move the baseball event to 08:00 pm", r"RescheduleAlertAlt")

    def test_reschedule_the_next_event_two_hours_earl(self):
        self._assert_adapt(r"reschedule the next event two hours earlier", r"RescheduleAlertAlt")

    def test_extend_the_pizza_timer_by_2_minutes(self):
        self._assert_adapt(r"extend the pizza timer by 2 minutes", r"RescheduleAlertAlt")

    def test_decrease_the_bread_timer_by_5_minutes(self):
        self._assert_adapt(r"decrease the bread timer by 5 minutes", r"RescheduleAlertAlt")

class TestAdapt12_Changeproperties(_IntentRoutingMixin, TestCase):
    """Adapt intent: ChangeProperties"""
    def test_reschedule_the_wake_alarm_to_every_monda(self):
        self._assert_adapt(r"reschedule the wake alarm to every Monday and Tuesday", r"ChangeProperties")

    def test_change_the_pill_reminder_frequency_to_4_(self):
        self._assert_adapt(r"change the pill reminder frequency to 4 hours", r"ChangeProperties")

    def test_change_the_baseball_event_priority_to_10(self):
        self._assert_adapt(r"change the baseball event priority to 10", r"ChangeProperties")

class TestAdapt13_Changemediaproperties(_IntentRoutingMixin, TestCase):
    """Adapt intent: ChangeMediaProperties"""
    def test_audible_adjourn(self):
        self._assert_adapt(r"audible adjourn", r"ChangeMediaProperties")

    def test_audible_adjourn_next(self):
        self._assert_adapt(r"audible adjourn next", r"ChangeMediaProperties")

class TestAdapt14_Listalerts(_IntentRoutingMixin, TestCase):
    """Adapt intent: ListAlerts"""
    def test_tell_me_my_pending_alarms(self):
        self._assert_adapt(r"tell me my pending alarms", r"ListAlerts")

    def test_what_are_my_upcoming_reminders(self):
        self._assert_adapt(r"what are my upcoming reminders", r"ListAlerts")

    def test_show_me_all_of_my_events(self):
        self._assert_adapt(r"show me all of my events", r"ListAlerts")

    def test_got_any_reminder_next_week(self):
        self._assert_adapt(r"got any reminder next week", r"ListAlerts")

    def test_are_there_any_alerts_between_4_pm_and_5_(self):
        self._assert_adapt(r"are there any alerts between 4 pm and 5 pm", r"ListAlerts")

class TestAdapt15_Timerstatus(_IntentRoutingMixin, TestCase):
    """Adapt intent: TimerStatus"""
    def test_how_much_time_is_left(self):
        self._assert_adapt(r"how much time is left", r"TimerStatus")

    def test_how_long_on_that_timer(self):
        self._assert_adapt(r"how long on that timer", r"TimerStatus")

    def test_what_is_the_timer_status(self):
        self._assert_adapt(r"what is the timer status", r"TimerStatus")

class TestAdapt16_Cancelalert(_IntentRoutingMixin, TestCase):
    """Adapt intent: CancelAlert"""
    def test_cancel_my_next_alarm(self):
        self._assert_adapt(r"cancel my next alarm", r"CancelAlert")

    def test_cancel_all_reminders(self):
        self._assert_adapt(r"cancel all reminders", r"CancelAlert")

    def test_clear_all_timers(self):
        self._assert_adapt(r"clear all timers", r"CancelAlert")

    def test_delete_my_next_event(self):
        self._assert_adapt(r"delete my next event", r"CancelAlert")

    def test_remove_my_next_alert(self):
        self._assert_adapt(r"remove my next alert", r"CancelAlert")

class TestAdapt17_Createlist(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateList"""
    def test_create_a_shopping_list(self):
        self._assert_adapt(r"create a shopping list", r"CreateList")

class TestAdapt18_Addlistsubitems(_IntentRoutingMixin, TestCase):
    """Adapt intent: AddListSubitems"""
    def test_add_things_to_the_shopping_list(self):
        self._assert_adapt(r"add things to the shopping list", r"AddListSubitems")

class TestAdapt19_Querylistnames(_IntentRoutingMixin, TestCase):
    """Adapt intent: QueryListNames"""
    def test_which_lists_are_stored(self):
        self._assert_adapt(r"which lists are stored", r"QueryListNames")

class TestAdapt20_Querytodoentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: QueryTodoEntries"""
    def test_anything_todo_query_todo(self):
        self._assert_adapt(r"anything todo? - query - todo", r"QueryTodoEntries")

    def test_is_there_something_todo(self):
        self._assert_adapt(r"is there something todo?", r"QueryTodoEntries")

class TestAdapt21_Querylistentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: QueryListEntries"""
    def test_what_items_are_on_my_shopping_list(self):
        self._assert_adapt(r"what items are on my shopping list", r"QueryListEntries")

class TestAdapt22_Deletelistentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: DeleteListEntries"""
    def test_drop_items_from_the_shopping_list(self):
        self._assert_adapt(r"drop items from the shopping list", r"DeleteListEntries")

    def test_drop_the_shopping_list(self):
        self._assert_adapt(r"drop the shopping list", r"DeleteListEntries")

    def test_delete_list(self):
        self._assert_adapt(r"delete list", r"DeleteListEntries")

class TestAdapt23_Deletelist(_IntentRoutingMixin, TestCase):
    """Adapt intent: DeleteList"""
    def test_drop_items_from_the_shopping_list(self):
        self._assert_adapt(r"drop items from the shopping list", r"DeleteList")

    def test_drop_the_shopping_list(self):
        self._assert_adapt(r"drop the shopping list", r"DeleteList")

    def test_delete_list(self):
        self._assert_adapt(r"delete list", r"DeleteList")

class TestAdapt24_Deletetodoentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: DeleteTodoEntries"""
    def test_remove_walk_the_dog_note(self):
        self._assert_adapt(r"remove walk the dog note", r"DeleteTodoEntries")

    def test_remove_todo_entries(self):
        self._assert_adapt(r"remove todo entries", r"DeleteTodoEntries")

    def test_remove_all_memos(self):
        self._assert_adapt(r"remove all memos", r"DeleteTodoEntries")

class TestAdapt25_Calendarlist(_IntentRoutingMixin, TestCase):
    """Adapt intent: CalendarList"""
    def test_which_calendars_are_available(self):
        self._assert_adapt(r"which calendars are available", r"CalendarList")

class TestAdapt26_Davsync(_IntentRoutingMixin, TestCase):
    """Adapt intent: DAVSync"""
    def test_download(self):
        self._assert_adapt(r"download", r"DAVSync")

class TestSimple27_Example_messages(_IntentRoutingMixin, TestCase):
    """Simple intent: example_messages"""
    def test_alarm_in_30_minutes(self):
        self._assert_simple(r"Alarm in 30 minutes")

    def test_wake_me_up_every_monday_and_thursday_at_(self):
        self._assert_simple(r"wake me up every monday and thursday at 9 AM.")

    def test_create_an_alarm_for_10_daily(self):
        self._assert_simple(r"create an alarm for 10 daily")

    def test_set_an_alarm_for_9_am_every_tuesday(self):
        self._assert_simple(r"set an alarm for 9 AM every tuesday")

    def test_set_an_alarm_for_8_am_on_weekdays(self):
        self._assert_simple(r"set an alarm for 8 AM on weekdays")
