"""E2E intent-routing tests for ovos-skill-alerts.

Originally auto-generated by tools/gen_ovoscope_tests.py (that generator no
longer exists in this repo). This file is now HAND-MAINTAINED -- the issue
#138 skip-audit triage and the follow-up defect fixes hand-edited utterances,
xfail reasons, and fixtures directly. If a generator script is ever
reintroduced, do not blindly re-run it over this file; it will clobber the
hand edits (corrected utterances, real-defect xfails referencing filed
issues, the store-isolation fixture below).

Run: pytest test/end2end/ -v
"""
import os
import shutil
import tempfile
import unittest
from unittest import TestCase

import pytest

from ovos_bus_client.message import Message
from ovos_bus_client.session import Session
from ovoscope import CaptureSession, End2EndTest, get_minicroft

SKILL_ID = "ovos-skill-alerts.openvoiceos"
LANG = "en-US"

# A single MiniCroft is booted once for the whole module and shared across
# every TestCase below. Booting one per class (the original generated
# pattern) meant ~30 separate MiniCroft boots per CI run, which is what made
# this suite time out / get killed in CI even with parallel workers disabled.
_MODULE_MINICROFT = None

# The skill persists its alert/todo-list store (alerts.json) under the
# process's XDG data dir, keyed only by skill_id -- NOT per test run. Left
# alone, that file lives at a machine-global path
# (~/.local/share/mycroft/filesystem/skills/<skill_id>/alerts.json) and
# accumulates indefinitely across every local run and every CI job that
# doesn't already isolate HOME/XDG_DATA_HOME, making any test whose
# behavior depends on "does this alert/list already exist" nondeterministic
# (see the DeleteList/DeleteListEntries xfails below, and issue #138's
# state-leak investigation). Point XDG_DATA_HOME at a fresh tmpdir for the
# whole module run so every invocation of this file starts from a
# genuinely empty store, regardless of what accumulated on disk from any
# other process.
_ISOLATED_XDG_DATA_HOME = None
_ORIGINAL_XDG_DATA_HOME = None


def setUpModule():
    global _MODULE_MINICROFT, _ISOLATED_XDG_DATA_HOME, _ORIGINAL_XDG_DATA_HOME
    _ORIGINAL_XDG_DATA_HOME = os.environ.get("XDG_DATA_HOME")
    _ISOLATED_XDG_DATA_HOME = tempfile.mkdtemp(prefix="ovos-skill-alerts-test-xdg-")
    os.environ["XDG_DATA_HOME"] = _ISOLATED_XDG_DATA_HOME
    _MODULE_MINICROFT = get_minicroft([SKILL_ID])


def tearDownModule():
    global _MODULE_MINICROFT, _ISOLATED_XDG_DATA_HOME, _ORIGINAL_XDG_DATA_HOME
    if _MODULE_MINICROFT is not None:
        _MODULE_MINICROFT.stop()
        _MODULE_MINICROFT = None
    if _ORIGINAL_XDG_DATA_HOME is None:
        os.environ.pop("XDG_DATA_HOME", None)
    else:
        os.environ["XDG_DATA_HOME"] = _ORIGINAL_XDG_DATA_HOME
    if _ISOLATED_XDG_DATA_HOME is not None:
        shutil.rmtree(_ISOLATED_XDG_DATA_HOME, ignore_errors=True)
        _ISOLATED_XDG_DATA_HOME = None


class _IntentRoutingMixin:
    """Shared MiniCroft setup."""

    @classmethod
    def setUpClass(cls):
        cls.minicroft = _MODULE_MINICROFT

    @classmethod
    def tearDownClass(cls):
        pass


    def _assert_intent(self, utterance: str, intent_msg_type: str, pipeline: list):
        """Fire an utterance and assert on a SUBSET of the resulting bus
        traffic: the intent matched, plus at least one visible side effect
        (speak / GUI / audio cue / a follow-up question via get_response).

        This deliberately does NOT assert a literal, fully-ordered
        ``expected_messages`` sequence. ovos-skill-alerts' handlers commonly
        ask a clarifying follow-up question (``get_response``) for
        under-specified utterances (e.g. "set an alarm" with no time), which
        produces a different, still-correct, message sequence than a fully
        resolved one-shot command. Asserting the literal sequence made most
        of this suite fail/flap on real (correct) skill behavior. See the
        ovos-skill-personal PR #113 wire-name/sequence-drift discussion for
        the same pattern in another skill.
        """
        session = Session(f"e2e-en_us-{hash(utterance)}-{hash(intent_msg_type)}")
        session.lang = LANG
        session.pipeline = pipeline
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        capture = CaptureSession(self.minicroft)
        capture.capture(message, timeout=30)
        messages = capture.finish()
        types = [m.msg_type for m in messages]
        self.assertIn(intent_msg_type, types)
        side_effects = ("speak", "gui.", "mycroft.audio.play_sound",
                        "skill.converse.get_response")
        self.assertTrue(
            any(any(se in t for se in side_effects) for t in types),
            f"no visible side effect for {utterance!r} -> {types}",
        )

    def _assert_padatious(self, utterance: str, intent_file: str):
        # The bus intent-matched message type is the padatious intent name
        # WITHOUT its file extension (e.g. "missed_alerts", not
        # "missed_alerts.intent") -- OVOS strips it when emitting
        # "<skill_id>:<intent_name>". Accept callers passing either form.
        intent_name = intent_file[:-len(".intent")] if intent_file.endswith(".intent") else intent_file
        intent_msg_type = f"{SKILL_ID}:{intent_name}"
        self._assert_intent(utterance, intent_msg_type, [
            "ovos-padatious-pipeline-plugin-high",
            "ovos-padatious-pipeline-plugin-medium",
            "ovos-padatious-pipeline-plugin-low",
        ])

    def _assert_adapt(self, utterance: str, intent_label: str = ''):
        intent_msg_type = f"{SKILL_ID}:{intent_label}"
        self._assert_intent(utterance, intent_msg_type, [
            "ovos-adapt-pipeline-plugin-high",
            "ovos-adapt-pipeline-plugin-medium",
            "ovos-adapt-pipeline-plugin-low",
        ])

    def _seed_list_with_item(self, list_name: str, item_name: str):
        """Create a TODO list (if needed) and add one child item to it
        directly via the AlertManager API, bypassing the interactive
        get_response cascade that AddListSubitems' real intent handler uses
        (there is no scripted answer to feed it in this end2end harness).

        This exists because DeleteList/DeleteListEntries's own
        `_resolve_requested_alert` filters candidate TODO lists down to
        ones that HAVE CHILDREN (`filter(lambda alert: alert.children,
        alerts)`) whenever the utterance's vocab includes "list" -- an
        empty list is invisible to both intents and the handler silently
        returns without speaking. Each caller must give its list a unique
        name so parallel/sequential tests against the shared module
        MiniCroft don't consume each other's single item.
        """
        from ovos_skill_alerts.util import AlertType
        from ovos_skill_alerts.util.alert import Alert

        skill = self.minicroft.plugin_skills[SKILL_ID].instance
        parents = skill._get_alerts_list(AlertType.TODO, name=list_name)
        if not parents:
            self._fire_adapt(f"create a {list_name} list")
            parents = skill._get_alerts_list(AlertType.TODO, name=list_name)
        assert parents, f"failed to create/find TODO list {list_name!r}"
        parent = parents[0]
        child = Alert.create(
            alert_name=item_name,
            alert_type=AlertType.TODO,
            context=dict(related_to=parent.ident),
            lang=LANG,
        )
        skill.alert_manager.add_alert(child)

    def _fire_adapt(self, utterance: str):
        """Fire an utterance through the adapt-only pipeline with no
        assertion -- used purely to set up state (e.g. create a todo list)
        ahead of a test that needs it to already exist, without pulling in
        an interactive get_response mock.
        """
        session = Session(f"e2e-en_us-seed-{hash(utterance)}")
        session.lang = LANG
        session.pipeline = [
            "ovos-adapt-pipeline-plugin-high",
            "ovos-adapt-pipeline-plugin-medium",
            "ovos-adapt-pipeline-plugin-low",
        ]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        capture = CaptureSession(self.minicroft)
        capture.capture(message, timeout=30)
        capture.finish()

    def _assert_simple(self, utterance: str):
        """Fire an utterance and assert a "speak" response appears in the
        bus trace, as a SUBSET check (see _assert_intent's docstring for why
        a literal fully-ordered ``expected_messages`` sequence is not used
        here: these utterances legitimately produce follow-up questions /
        extra bus traffic beyond a bare 2-message request/response pair,
        e.g. "❌ got 4 messages, expected 2" when pinned to a strict
        End2EndTest(expected_messages=[...]) sequence).
        """
        session = Session(f"e2e-en_us-simple-{hash(utterance)}")
        session.lang = LANG
        # Unlike _assert_adapt/_assert_padatious, these "simple" rows are
        # not pinned to one pipeline stage -- they need the full default
        # order so either Adapt or Padatious can match. Leaving
        # session.pipeline unset previously fell back to a pipeline that
        # does not include this skill's plugins, producing
        # 'ovos.intent.unmatched' for every row in this class regardless of
        # utterance (auto-generation defect, same family as the
        # adapt-only-pin rows -- see _assert_adapt/_assert_padatious).
        session.pipeline = [
            "ovos-padatious-pipeline-plugin-high",
            "ovos-adapt-pipeline-plugin-high",
            "ovos-padatious-pipeline-plugin-medium",
            "ovos-adapt-pipeline-plugin-medium",
            "ovos-padatious-pipeline-plugin-low",
            "ovos-adapt-pipeline-plugin-low",
        ]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        capture = CaptureSession(self.minicroft)
        capture.capture(message, timeout=30)
        messages = capture.finish()
        types = [m.msg_type for m in messages]
        self.assertTrue(
            any("speak" in t for t in types),
            f"no speak message for {utterance!r} -> {types}",
        )


class TestPadatious1_Missed_alerts_intent(_IntentRoutingMixin, TestCase):
    """Padatious intent: missed_alerts.intent"""
    def test_did_i_miss_any_alarms(self):
        self._assert_padatious(r"did i miss any alarms", r"missed_alerts.intent")

    def test_missed_any_reminder(self):
        self._assert_padatious(r"missed any reminder", r"missed_alerts.intent")

    def test_have_i_missed_any_timers(self):
        self._assert_padatious(r"have i missed any timers", r"missed_alerts.intent")

    def test_miss_any_events(self):
        self._assert_padatious(r"miss any events", r"missed_alerts.intent")

    def test_did_i_miss_a_alarm(self):
        self._assert_padatious(r"did i miss a alarm", r"missed_alerts.intent")

class TestAdapt2_Createalarm(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateAlarm"""
    def test_set_an_alarm(self):
        self._assert_adapt(r"set an alarm", r"CreateAlarm")

    def test_create_a_playback_alarm_every_weekday_wi(self):
        self._assert_adapt(r"create a playback alarm every weekday with my test script until next tuesday", r"CreateAlarm")

    @pytest.mark.xfail(strict=True, reason="issue #155: relative/absolute time argument makes the utterance unmatched under the full default pipeline -- real skill defect (Adapt confidence dilution / unhandled duration vocab), confirmed via control-pair evidence (bare phrase matches, +argument phrase doesn't: 'set an alarm' matches CreateAlarm, 'alarm in an hour' matches nothing). See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_alarm_in_an_hour(self):
        self._assert_adapt(r"alarm in an hour", r"CreateAlarm")

    def test_alarm_daily_for_the_next_week_at_9_am(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"set an alarm daily for the next week at 9 AM", r"CreateAlarm")

    def test_make_a_10_am_weekend_alarm(self):
        self._assert_adapt(r"make a 10 am weekend alarm", r"CreateAlarm")

class TestAdapt3_Createalarmalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateAlarmAlt"""
    def test_set_an_alarm(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"wake me up", r"CreateAlarmAlt")

    def test_create_a_playback_alarm_every_weekday_wi(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"wake me up with a playable script every weekday until next tuesday", r"CreateAlarmAlt")

    def test_alarm_in_an_hour(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"wake us up every weekday at 6 am", r"CreateAlarmAlt")

    def test_alarm_daily_for_the_next_week_at_9_am(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"wake me up daily for the next week at 9 AM", r"CreateAlarmAlt")

    def test_make_a_10_am_weekend_alarm(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"wake me up every weekend", r"CreateAlarmAlt")

class TestAdapt4_Createocpalarm(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateOcpAlarm"""
    def test_wake_me_up_with_music(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"set an alarm with music", r"CreateOcpAlarm")

class TestAdapt5_Createocpalarmalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateOcpAlarmAlt"""
    def test_wake_me_up_with_music(self):
        self._assert_adapt(r"wake me up with music", r"CreateOcpAlarmAlt")

class TestAdapt6_Createtimer(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateTimer"""
    def test_set_a_timer(self):
        self._assert_adapt(r"set a timer", r"CreateTimer")

    def test_start_a_timer(self):
        self._assert_adapt(r"start a timer", r"CreateTimer")

    def test_create_a_baking_timer(self):
        self._assert_adapt(r"create a baking timer", r"CreateTimer")

    def test_make_a_5_hour_timer(self):
        self._assert_adapt(r"make a 5 hour timer", r"CreateTimer")

class TestAdapt7_Createreminder(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateReminder"""
    def test_set_a_playback_reminder_to_take_out_the_(self):
        self._assert_adapt(r"set a playback reminder to take out the trash daily at 5 pm until november", r"CreateReminder")

    def test_set_a_script_reminder_for_weekends_at_5_(self):
        self._assert_adapt(r"set a script reminder for weekends at 5 till next week", r"CreateReminder")

    def test_create_a_reminder_to_go_to_work_at_9_am_(self):
        self._assert_adapt(r"create a reminder to go to work at 9 am daily for the next month", r"CreateReminder")

    def test_remind_me_to_go_to_work_weekday_mornings(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"create a reminder to go to work every weekday morning at 8", r"CreateReminder")

    def test_remind_me_every_day_to_check_for_test_fa(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"set a reminder every day to check for test failures until 2024", r"CreateReminder")

class TestAdapt8_Createreminderalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateReminderAlt"""
    def test_set_a_playback_reminder_to_take_out_the_(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"tell me to take out the trash daily at 5 pm until november", r"CreateReminderAlt")

    def test_set_a_script_reminder_for_weekends_at_5_(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"tell me to check for test failures every day until 2024", r"CreateReminderAlt")

    def test_create_a_reminder_to_go_to_work_at_9_am_(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"tell me to walk the dog every weekday at 8", r"CreateReminderAlt")

    def test_remind_me_to_go_to_work_weekday_mornings(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"tell me to go to work every weekday morning", r"CreateReminderAlt")

    def test_remind_me_every_day_to_check_for_test_fa(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"tell me to feed the cat every morning at 7", r"CreateReminderAlt")

class TestAdapt9_Createevent(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateEvent"""
    @pytest.mark.xfail(strict=True, reason="issue #155: 'I have a work event next tuesday at 7 PM' matches no intent (ovos.intent.unmatched) under the adapt-only pipeline -- confirmed independently, deterministic in isolation (not order-dependent). A control pair with the sibling row in this same class shows the ambiguity is time/argument-shape related, consistent with the other #155 findings: 'I have an appointment at 9 PM every weekend night until next year' (below) matches CreateEvent correctly, so the CreateEvent vocab path works in general -- this specific phrasing/argument combination does not. Real skill defect, not a test artifact. See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_i_have_a_work_event_next_tuesday_at_7_pm(self):
        self._assert_adapt(r"I have a work event next tuesday at 7 PM", r"CreateEvent")

    def test_i_have_an_appointment_at_9_pm_every_week(self):
        self._assert_adapt(r"I have an appointment at 9 PM every weekend night until next year", r"CreateEvent")

    def test_create_a_daily_event_to_join_zoom_at_1_p(self):
        # issue #138/#151-era triage marked this row xfail (both a
        # pipeline-pin-mismatch xfail(strict=True) and later a
        # xfail(strict=False) "pytest-timeout under suite load" reason) --
        # both were wrong. A standalone probe (fresh MiniCroft, this
        # utterance alone, adapt-only pipeline pin matching _assert_adapt)
        # shows the ORIGINAL auto-generated utterance routes correctly to
        # CreateEvent with no timeout. Restored as a plain, unmarked pass.
        self._assert_adapt(r"create a daily event to join zoom at 1 PM for the next year", r"CreateEvent")

class TestAdapt10_Reschedulealert(_IntentRoutingMixin, TestCase):
    """Adapt intent: RescheduleAlert"""
    @pytest.mark.xfail(strict=True, reason="issue #155: relative/absolute time argument makes the utterance unmatched under the full default pipeline -- real skill defect (Adapt confidence dilution / unhandled duration vocab), confirmed via control-pair evidence ('move the baseball event' matches RescheduleAlert, 'move the baseball event to 08:00 pm' matches nothing). See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_move_the_baseball_event_to_08_00_pm(self):
        self._assert_adapt(r"move the baseball event to 08:00 pm", r"RescheduleAlert")

    def test_reschedule_the_next_event_two_hours_earl(self):
        self._assert_adapt(r"reschedule the next event two hours earlier", r"RescheduleAlert")

    @pytest.mark.xfail(strict=True, reason="issue #155: relative/absolute time argument makes the utterance unmatched under the full default pipeline -- real skill defect (Adapt confidence dilution / unhandled duration vocab), confirmed via control-pair evidence ('adjust the pizza timer' matches RescheduleAlert, 'adjust the pizza timer by 2 minutes' matches nothing). See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_extend_the_pizza_timer_by_2_minutes(self):
        self._assert_adapt(r"extend the pizza timer by 2 minutes", r"RescheduleAlert")

    @pytest.mark.xfail(strict=True, reason="issue #155: relative/absolute time argument makes the utterance unmatched under the full default pipeline -- real skill defect (Adapt confidence dilution / unhandled duration vocab), confirmed via control-pair evidence ('decrease the bread timer' matches a sibling intent, 'decrease the bread timer by 5 minutes' matches nothing at all). See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_decrease_the_bread_timer_by_5_minutes(self):
        self._assert_adapt(r"decrease the bread timer by 5 minutes", r"RescheduleAlert")

class TestAdapt11_Reschedulealertalt(_IntentRoutingMixin, TestCase):
    """Adapt intent: RescheduleAlertAlt"""
    def test_move_the_baseball_event_to_08_00_pm(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"shorten the timer", r"RescheduleAlertAlt")

    @pytest.mark.xfail(strict=True, reason="issue #155: relative/absolute time argument makes the utterance unmatched under the full default pipeline -- real skill defect (Adapt confidence dilution / unhandled duration vocab), confirmed via control-pair evidence ('reschedule the next event' matches a sibling intent, 'reschedule the next event two hours earlier' matches nothing at all under RescheduleAlertAlt). See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_reschedule_the_next_event_two_hours_earl(self):
        self._assert_adapt(r"reschedule the next event two hours earlier", r"RescheduleAlertAlt")

    def test_extend_the_pizza_timer_by_2_minutes(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"increase the pizza timer", r"RescheduleAlertAlt")

    def test_decrease_the_bread_timer_by_5_minutes(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        #
        # NOTE: an earlier candidate here, "make the timer sooner", was
        # investigated further after it flipped to CreateTimer only when
        # run as part of the full suite (not in isolation). A controlled
        # experiment (poison with "set a timer", then fire the candidate,
        # once with the skill's persistent alert store left as-is and once
        # with it forcibly wiped to {} in between) produced byte-identical
        # Adapt confidence scores in both cases -- ruling out skill/store
        # state. Root cause: "make the timer sooner" is genuinely ambiguous
        # by vocab alone ("make"=create-vocab + "timer"=timer-vocab also
        # fully satisfies CreateTimer's own requirements), the same defect
        # class this PR is fixing elsewhere. "sooner the timer" avoids any
        # create-vocab word so it cannot satisfy CreateTimer.
        self._assert_adapt(r"the bread timer sooner", r"RescheduleAlertAlt")

class TestAdapt12_Changeproperties(_IntentRoutingMixin, TestCase):
    """Adapt intent: ChangeProperties"""
    def test_reschedule_the_wake_alarm_to_every_monda(self):
        self._assert_adapt(r"reschedule the wake alarm to every Monday and Tuesday", r"ChangeProperties")

    def test_change_the_pill_reminder_frequency_to_4_(self):
        self._assert_adapt(r"change the pill reminder frequency to 4 hours", r"ChangeProperties")

    def test_change_the_baseball_event_priority_to_10(self):
        self._assert_adapt(r"change the baseball event priority to 10", r"ChangeProperties")

class TestAdapt13_Changemediaproperties(_IntentRoutingMixin, TestCase):
    """Adapt intent: ChangeMediaProperties"""
    def test_audible_adjourn(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"adjourn the next playable alarm", r"ChangeMediaProperties")

    def test_audible_adjourn_next(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"change the playable event", r"ChangeMediaProperties")

class TestAdapt14_Listalerts(_IntentRoutingMixin, TestCase):
    """Adapt intent: ListAlerts"""
    def test_tell_me_my_pending_alarms(self):
        self._assert_adapt(r"tell me my pending alarms", r"ListAlerts")

    def test_what_are_my_upcoming_reminders(self):
        self._assert_adapt(r"what are my upcoming reminders", r"ListAlerts")

    def test_show_me_all_of_my_events(self):
        self._assert_adapt(r"show me all of my events", r"ListAlerts")

    def test_got_any_reminder_next_week(self):
        self._assert_adapt(r"got any reminder next week", r"ListAlerts")

    def test_are_there_any_alerts_between_4_pm_and_5_(self):
        self._assert_adapt(r"are there any alerts between 4 pm and 5 pm", r"ListAlerts")

class TestAdapt15_Timerstatus(_IntentRoutingMixin, TestCase):
    """Adapt intent: TimerStatus"""
    def test_how_much_time_is_left(self):
        self._assert_adapt(r"how much time is left", r"TimerStatus")

    def test_how_long_on_that_timer(self):
        self._assert_adapt(r"how long on that timer", r"TimerStatus")

    def test_what_is_the_timer_status(self):
        self._assert_adapt(r"what is the timer status", r"TimerStatus")

class TestAdapt16_Cancelalert(_IntentRoutingMixin, TestCase):
    """Adapt intent: CancelAlert"""
    def test_cancel_my_next_alarm(self):
        self._assert_adapt(r"cancel my next alarm", r"CancelAlert")

    def test_cancel_all_reminders(self):
        self._assert_adapt(r"cancel all reminders", r"CancelAlert")

    def test_clear_all_timers(self):
        self._assert_adapt(r"clear all timers", r"CancelAlert")

    def test_delete_my_next_event(self):
        self._assert_adapt(r"delete my next event", r"CancelAlert")

    def test_remove_my_next_alert(self):
        self._assert_adapt(r"remove my next alert", r"CancelAlert")

class TestAdapt17_Createlist(_IntentRoutingMixin, TestCase):
    """Adapt intent: CreateList"""
    def test_create_a_shopping_list(self):
        self._assert_adapt(r"create a shopping list", r"CreateList")

class TestAdapt18_Addlistsubitems(_IntentRoutingMixin, TestCase):
    """Adapt intent: AddListSubitems"""
    def test_add_things_to_the_shopping_list(self):
        self._assert_adapt(r"add things to the shopping list", r"AddListSubitems")

class TestAdapt19_Querylistnames(_IntentRoutingMixin, TestCase):
    """Adapt intent: QueryListNames"""
    def test_which_lists_are_stored(self):
        self._assert_adapt(r"which lists are stored", r"QueryListNames")

class TestAdapt20_Querytodoentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: QueryTodoEntries"""
    def test_anything_todo_query_todo(self):
        self._assert_adapt(r"anything todo? - query - todo", r"QueryTodoEntries")

    def test_is_there_something_todo(self):
        self._assert_adapt(r"is there something todo?", r"QueryTodoEntries")

class TestAdapt21_Querylistentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: QueryListEntries"""
    def test_what_items_are_on_my_shopping_list(self):
        self._assert_adapt(r"what items are on my shopping list", r"QueryListEntries")

class TestAdapt22_Deletelistentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: DeleteListEntries"""
    # issue #138: the original triage's strict=False "ORDER-DEPENDENT on
    # suite state" xfails on this class were a real symptom, but the wrong
    # root cause. _resolve_requested_alert filters candidate TODO lists to
    # ones WITH CHILDREN whenever "list" vocab is present -- an empty list
    # is invisible to DeleteListEntries and the handler no-ops silently. All
    # 3 rows below previously targeted the same "shopping list", so
    # whichever ran first (module-shared MiniCroft/store) consumed the only
    # seeded state and the rest failed the side-effect assert -- not an
    # Adapt ambiguity at all. Fixed by giving each row its own seeded,
    # non-competing list (see _seed_list_with_item), making all 3
    # deterministic regardless of run order. No xfail needed.
    def test_drop_items_from_the_shopping_list(self):
        self._seed_list_with_item("shopping", "milk")
        self._assert_adapt(r"drop items from the shopping list", r"DeleteListEntries")

    def test_drop_the_shopping_list(self):
        self._seed_list_with_item("grocery", "eggs")
        self._assert_adapt(r"remove items from the grocery list", r"DeleteListEntries")

    def test_delete_list(self):
        self._seed_list_with_item("hardware", "nails")
        self._assert_adapt(r"drop items from the hardware list", r"DeleteListEntries")

class TestAdapt23_Deletelist(_IntentRoutingMixin, TestCase):
    """Adapt intent: DeleteList"""
    # issue #138: same root cause as TestAdapt22_Deletelistentries above --
    # _resolve_requested_alert requires the target TODO list to have
    # children, and the 3 rows below previously competed for the same
    # "shopping list". Fixed the same way: separate seeded lists per row.
    # Also: "drop items from the X list" (with "items") satisfies
    # DeleteListEntries's own vocab requirement too and DeleteListEntries
    # requires strictly more matched words (delete+items+list vs
    # delete+list), so it reliably outscores DeleteList on that phrasing --
    # that WAS a genuine ambiguous-utterance defect in the original row,
    # now avoided by dropping "items" from this class's utterances entirely.
    def test_drop_items_from_the_shopping_list(self):
        self._seed_list_with_item("pantry", "flour")
        self._assert_adapt(r"drop the pantry list", r"DeleteList")

    def test_drop_the_shopping_list(self):
        self._seed_list_with_item("bakery", "sugar")
        self._assert_adapt(r"drop the bakery list", r"DeleteList")

    def test_delete_list(self):
        self._seed_list_with_item("office", "stapler")
        self._assert_adapt(r"delete the office list", r"DeleteList")

class TestAdapt24_Deletetodoentries(_IntentRoutingMixin, TestCase):
    """Adapt intent: DeleteTodoEntries"""
    def test_remove_walk_the_dog_note(self):
        self._assert_adapt(r"remove walk the dog note", r"DeleteTodoEntries")

    def test_remove_todo_entries(self):
        self._assert_adapt(r"remove todo entries", r"DeleteTodoEntries")

    def test_remove_all_memos(self):
        self._assert_adapt(r"remove all memos", r"DeleteTodoEntries")

class TestAdapt25_Calendarlist(_IntentRoutingMixin, TestCase):
    """Adapt intent: CalendarList"""
    def test_which_calendars_are_available(self):
        self._assert_adapt(r"which calendars are available", r"CalendarList")

class TestAdapt26_Davsync(_IntentRoutingMixin, TestCase):
    """Adapt intent: DAVSync"""
    def test_download(self):
        # issue #138 triage: original auto-generated utterance did not
        # route to this intent under the adapt-only pipeline pin (verified
        # locally with a standalone probe against every candidate phrasing).
        # Replaced with a phrasing confirmed to route correctly, keeping
        # equivalent test intent/coverage rather than dropping the row.
        self._assert_adapt(r"synchronize my calendar", r"DAVSync")

class TestSimple27_Example_messages(_IntentRoutingMixin, TestCase):
    """Simple intent: example_messages"""
    @pytest.mark.xfail(strict=True, reason="issue #155: relative-duration alarms are unsupported -- 'Alarm in 30 minutes' matches no intent (ovos.intent.unmatched) under either Adapt or Padatious, and every relative-duration alarm phrasing tried ('set an alarm in 30 minutes', 'set an alarm for 30 minutes from now') also comes back unmatched, while the equivalent relative-duration TIMER phrasing ('Start a bread timer for 30 minutes.') is a real registered skill example. Real skill defect, not a test artifact -- do not replace this row with a differently-worded alarm utterance, it is the only in-repo evidence of the gap. See https://github.com/OpenVoiceOS/ovos-skill-alerts/issues/155.")
    def test_alarm_in_30_minutes(self):
        self._assert_simple(r"Alarm in 30 minutes")

    def test_wake_me_up_every_monday_and_thursday_at_(self):
        self._assert_simple(r"wake me up every monday and thursday at 9 AM.")

    def test_create_an_alarm_for_10_daily(self):
        self._assert_simple(r"create an alarm for 10 daily")

    def test_set_an_alarm_for_9_am_every_tuesday(self):
        self._assert_simple(r"set an alarm for 9 AM every tuesday")

    def test_set_an_alarm_for_8_am_on_weekdays(self):
        self._assert_simple(r"set an alarm for 8 AM on weekdays")
